env:
 es2021: true
 node: true
extends:
 - eslint:recommended
 - plugin:@typescript-eslint/recommended
 - prettier/@typescript-eslint
 - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
 ecmaVersion: latest
 sourceType: module
plugins:
 - '@typescript-eslint'
rules:
 {
  '@typescript-eslint/no-non-null-assertion': 'off',
  'no-case-declarations': 'off',
  '@typescript-eslint/ban-ts-comment': 'off',
  '@typescript-eslint/no-var-requires': 'off'
  'prettier/prettier': ['error', {}, { 'usePrettierrc': true }]
 }